import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../styles/globals.scss";

import {
  initServerI18next,
  getT,
  getResources,
  generateI18nStaticParams,
} from "next-i18next/server";
import { I18nProvider } from "next-i18next/client";
import i18nConfig from "../../i18n.config";

//Translation
initServerI18next(i18nConfig);

type Props = {
  params: Promise<{ lng: string }>;
};

export const metadata: Metadata = {
  title: "CaBric Engineering",
  description: "Generated by create next app",
};

const regular = localFont({
  src: "../fonts/SF-Pro-Display-Regular.ttf",
  variable: "--regular-font",
});

const medium = localFont({
  src: "../fonts/SF-Pro-Display-Medium.ttf",
  variable: "--medium-font",
})

const ttnormal = localFont({
  src: "../fonts/TTNormsProMono-Medium.ttf",
  variable: "--ttnormal",
});

const ttbold = localFont({
  src: "../fonts/TTNormsProMono-DemiBold.ttf",
  variable: "--ttbold",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${regular.variable} ${medium.variable} ${ttnormal.variable} ${medium.variable}`}>
      <body>{children}</body>
    </html>
  );
}
